apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: k8s-quiz
    app.kubernetes.io/type: secret
  name: k8s-quiz-configmap-env
data:
  DEPLOYMENT_NAME: "k8s-quiz"
  HIDE_QUIZ: "true"
