apiVersion: v1
kind: Service
metadata:
  name: k8s-quiz
  labels:
    app.kubernetes.io/name: k8s-quiz
    app.kubernetes.io/type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: k8s-quiz
    app.kubernetes.io/type: pod
