apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment
  labels:
    app.kubernetes.io/name: k8s-deployment
    app.kubernetes.io/instance: k8s-deployment
    app.kubernetes.io/type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: k8s-deployment
    app.kubernetes.io/instance: k8s-deployment 
    app.kubernetes.io/type: pod
