apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-nginx
      image: nginx
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: SECRET_KEY
      command: ["/bin/sh"]
      args: ["-c", "echo \"<html><head><title>Secret Key</title></head><body><b>Secret Key : </b>\"$SECRET_KEY\"</body></html>\" > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"]

